[Service]
ExecStartPre=/usr/bin/python3 /storage/.config/am9-tailnet-firewall.py --config /storage/.config/am9-tailnet-firewall.json --apply
ExecStart=
ExecStart=/usr/bin/python3 /storage/.config/am9-tailnet-launch.py
RestartSec=60
